group_name: "dqn_distributed_test"
total_message: 15
stop_message: 2   # random put
actor:
  peer: {"learner": 1}
learner:
  peer: {"actor": 3}
redis:
  host_name: "localhost"
  port: 6379
rejoin:
  enable: True
  peers_update_frequency: 10
  minimal_peers: 1.0  # 1.0 - 0.1 available peers percentage (at least one alive peer)
  message_cache_for_rejoin: True
  max_wait_time_for_rejoin: 30  # second

  